# This is a basic workflow to help you get started with Actions

name: Build LaTeX document

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: "Graduation Project Book"
          root_file: "main.tex"
      - name: PDF Upload
        uses: actions/upload-artifact@v3
        with:
          name: graduation-project-book
          path: "Graduation Project Book/main.pdf"
          if-no-files-found: error